config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions' }

  root 'home#index'

  namespace :admin do
    root :to => "users#index"
    get '/users/search' => 'users#search'
    resources :users
    resources :teams
    resources :jobs
  end
  
  namespace :user do
    root to: "timesheets#index"
    resources :users
    resources :timesheets
    resources :leaves

  end

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  paginates_per 10
  belongs_to :user
  belongs_to :job
  auto_strip_attributes :description, :duration
  validates :description, length: {minimum: 5}
  validates :duration, presence: true, length: {minimum: 1}, numericality: {greater_than: 0}
  validates :working_date, presence: true

  def available_jobs
    return [] if user.available_jobs.blank?
    user.available_jobs
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :lockable
  paginates_per 10
  
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates :password_confirmation, presence: true, length: {minimum: 8}, :if => :password_required?
  belongs_to :team
  has_many :timesheets
  has_many :leaves
  
  alias_attribute :name, :email

  def full_name
    full_name = "#{first_name} #{last_name}"
    
    full_name.strip.empty? ? "Unknown" : full_name
  end
  
  def details
    team = Team.find_by_id(team_id)
    team_name = team.nil? ? "Unknown" : team.name
    "ID: #{id} - #{full_name} - #{team_name}"
  end
  
  def available_jobs
    self.team.jobs.where.not(state_id: State::TYPES[:completed]).order(:id) if self.team
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController
  before_filter :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end
  
  def create    
    @user = User.create(user_params)

    if @user.save
      flash[:notice] = "New user has been created!"
      UserMailer.welcome_to_strongtie(@user).deliver
      redirect_to admin_users_path
    else
      flash[:error] = "Error when trying to save. Please try again"
      render :new
    end
  end

  def index
    @users = User.all.order(:email).page params[:page]
  end
  
  def update
    sanitize_user_params
    if @user.update_without_password user_params
      flash[:notice] = "User has been updated successfully!"
      redirect_to admin_users_path
    else
      flash[:error] = "Error when trying to update #{@user.email}. Please try again"
      render :edit
    end
  end
  
  def destroy
    if @user != current_user
      @user.destroy
      flash[:notice] = "User has been deleted successfully!"
    else
      flash[:error] = "You can't delete yourself!"
    end
    
    render nothing: true #ajax call will reload index page
  end

  def search
    @users = User.where("email = ? or first_name = ? or last_name = ?", params[:email], params[:first_name], params[:last_name])
    @users = User.all.order(:email) if @users.empty? && search_params_empty?

    @users = @users.page params[:page]
    render :index
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def search_params_empty?
    [:email, :first_name, :last_name].inject(true) {|result, search_param| result && params[search_param].empty? }
  end

  def user_params
    params.require(:user).permit(:email,
                                 :first_name,
                                 :last_name,
                                 :password,
                                 :password_confirmation,
                                 :admin,
                                 :team_id)
  end
  
  def sanitize_user_params
    if user_params[:password].blank?
      user_params.delete :password
      user_params.delete :password_confirmation
    end
  end
end

app/controllers/user/leaves_controller.rb
class User::LeavesController < User::UsersController
  def index
    @leaves = Leave.all.order(leave_date: :desc).page params[:page] 
  end

  def new
    @leave = Leave.new
  end

  def create
    @leave = Leave.create(leave_params)
    @leave.user = @user
    @leave.status = State::LEAVE_TYPE[:new]
    if @leave.save
      flash[:notice] = "New leave has been created successfully!"
      redirect_to user_leaves_path
    else
      flash[:error] = "There is an error when creating new leave. Please try again!"
      render :new
    end
  end

  private

  def leave_params
    params.require(:leave).permit(
      :leave_date,
      :leave_type,
      :duration,
      :reason
    )
  end
end

app/controllers/user/timesheets_controller.rb
class User::TimesheetsController < User::UsersController
  before_filter :set_timesheet, only: [:update, :show, :edit, :destroy]
  def index
    @timesheets = Timesheet.where(user_id: @user.id).order(:working_date => :desc).page params[:page]
  end
  
  def new
    @timesheet = Timesheet.new
  end
  
  def create
    @timesheet = Timesheet.create(timesheet_params)
    @timesheet.user = @user
    if @timesheet.save
      flash[:notice] = "New work log has been created successfully!"
      redirect_to user_timesheets_path
    else
      flash[:error] = "Error when creating work log. Please try again"
      render :new
    end
  end
  
  def update
    respond_to do |format|
      if @timesheet.update timesheet_params
        format.html do
          flash[:notice] = "Work log has been updated successfully!"
          redirect_to user_timesheets_path
        end
        format.json {head :no_content}
      else
        format.html do
          flash[:notice] = "Error when updating work log. Please try again"
          render :edit
        end
        format.json {head 406}
      end
    end
  end
  
  def destroy
    if @timesheet.destroy
      flash[:notice] = "Work log has been deleted successfully!"
    else
      flash[:error] = "Error when deleting work log. Please try again"
    end
    
    render nothing: true
  end
  
  private
  def timesheet_params
    params.require(:timesheet).permit(
      :description,
      :working_date,
      :duration,
      :job_id,
      :work_type
    )
  end
  
  def set_timesheet
    @timesheet = Timesheet.find(params[:id])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_user_layout
  before_filter :set_user
  
  def set_user_layout
    self.class.layout "user/layout"
  end
  
  def update
    if @user.update_without_password user_params
      flash[:notice] = "Your profile has been updated successfully!"
    else
      flash[:error] = "Error when saving your profile. Please try again"
    end

    render :edit
  end
  
  private
  def set_user
    @user = current_user
  end
  
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :picture
    )
  end
end

app/views/user/timesheets/_form.html.haml
.article
  = form_for([:user, @timesheet], html: {class: "form-default"}) do |f|
    = show_error_messages_if_any @timesheet.errors.full_messages
    .form-group
      = render :partial => "public/common/jobs_dropdown", locals: {:f => f, :jobs => @user.available_jobs, :select_id => @timesheet.job_id}
    .form-group
      = f.label :work_type, "Type"
      = f.select :work_type, %w{Working Meeting Training}, {}, {class: "form-control"}
    .form-group
      = f.label :description
      = f.text_area :description, autofocus: true, class: "form-control"
    .form-group
      = f.label :duration
      = f.text_field :duration, autofocus: true, class: "form-control"
    .form-group
      = f.label :working_date
      = f.text_field :working_date, autofocus: true, class: "form-control datepicker", value: @timesheet.working_date ? format_date(@timesheet.working_date) : format_date(Date.today)

    .actions
      %button.btn.btn-primary{:type => "submit"}
        %i.fa.fa-send
          SAVE

:javascript
  enableDatePicker($(".datepicker"))

app/views/user/timesheets/_timesheet_view.html.haml
%tr
  %td.col-xs-1
    = editable [@user, timesheet], :working_date, :type => "combodate", value: format_date(timesheet.working_date), :url => "#{user_timesheet_path timesheet}"
  %td.column-duration
    = editable [@user, timesheet], :duration, :type =>  "text", :url => "#{user_timesheet_path timesheet}"
  %td.col-xs-3
    = editable [@user, timesheet], :job_id, :type => "select", :source => "#{timesheet.available_jobs.map {|job| {value: job.id, text: job.name}}.to_json}", :url => "#{user_timesheet_path timesheet}"
  %td.col-xs-1
    = editable [@user, timesheet], :work_type, :type => "select", :source => %w{Working Meeting Training}, :url => "#{user_timesheet_path timesheet}"
  %td.col-xs-5
    = editable [@user, timesheet], :description, :type => "textarea", :url => "#{user_timesheet_path timesheet}"

  %td.col-edit
    %span.badge.fa.fa-edit
      = link_to "Edit", "#{edit_link_for timesheet}", :class => "badge", :id => "edit-timesheet-#{timesheet.id}"
  %td.col-delete
    %span.badge.fa.fa-trash
      = link_to "Delete", "#", :class => "badge", :id => "delete-timesheet-#{timesheet.id}", "data-toggle" => "modal", "data-target" => "#delete-confirmation", "data-href" => "#{link_for timesheet}"

app/views/user/timesheets/edit.html.haml
.container
  .col-sm-6.col-md-offset-3
    %h2 Edit work log
    %hr
    = render partial: "form"

app/views/user/timesheets/index.html.haml
.container.clearfix
  = show_error_messages_if_any [flash[:error]]
  = show_notice_message_if_any flash[:notice]

  .add-button-link.btn-primary.fa.fa-plus
    = link_to "Log work", new_user_timesheet_path

  - if @timesheets.any?
    %table.table.table-bordered.table-striped
      - @timesheets.each do |timesheet|
        = render :partial => "timesheet_view", locals: {:timesheet => timesheet}

    .text-center
      = paginate @timesheets
      
= render :partial => "public/common/confirmation"
:javascript
  enableXEditable();

app/views/user/timesheets/new.html.haml
.container
  .col-sm-6.col-md-offset-3
    %h2 Create new work log
    %hr
    = render partial: "form"