config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions' }

  root 'home#index'

  namespace :admin do
    root :to => "users#index"
    get '/users/search' => 'users#search'
    resources :users
    resources :teams
    resources :jobs
  end
  
  namespace :user do
    root to: "timesheets#index"
    resources :users
    resources :timesheets
    resources :leaves

  end

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/views/layouts/admin/admin.html.haml
= render :partial => "layouts/head"
%body
  = render :partial => "layouts/header"
  .article
    .container.dashboard
      %div{:role => "tabpanel"}
        / Nav tabs
        %ul.nav.nav-tabs{:role => "tablist"}
          %li.col-xs-4{:role => "presentation"}
            = link_to "USERS", admin_users_path, :role => "tab"
          %li.col-xs-4{:role => "presentation"}
            = link_to "TEAMS", admin_teams_path, :role => "tab"
          %li.col-xs-4{:role => "presentation"}
            = link_to "JOBS", admin_jobs_path, :role => "tab"
  #main
    = yield
  = render :partial => "layouts/footer"

app/views/layouts/admin/admin_layout.html.haml
= render :partial => "layouts/head"
%body
  = render :partial => "layouts/header"
  .article
    .container.dashboard
      %div{:role => "tabpanel"}
        / Nav tabs
        %ul.nav.nav-tabs{:role => "tablist"}
          %li.col-xs-4{:role => "presentation"}
            = link_to "USERS", admin_users_path, :role => "tab"
          %li.col-xs-4{:role => "presentation"}
            = link_to "TEAMS", admin_teams_path, :role => "tab"
          %li.col-xs-4{:role => "presentation"}
            = link_to "JOBS", admin_jobs_path, :role => "tab"
  #main
    = yield
  = render :partial => "layouts/footer"

app/views/layouts/admin/layout.html.haml
= render :partial => "layouts/head"
%body
  = render :partial => "layouts/header"
  .article
    .container.dashboard
      %div{:role => "tabpanel"}
        / Nav tabs
        %ul.nav.nav-tabs{:role => "tablist"}
          %li.col-xs-4{:role => "presentation"}
            = link_to "USERS", admin_users_path, :role => "tab"
          %li.col-xs-4{:role => "presentation"}
            = link_to "TEAMS", admin_teams_path, :role => "tab"
          %li.col-xs-4{:role => "presentation"}
            = link_to "JOBS", admin_jobs_path, :role => "tab"
  #main
    = yield
  = render :partial => "layouts/footer"