config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions' }

  root 'home#index'

  namespace :admin do
    root :to => "users#index"
    get '/users/search' => 'users#search'
    resources :users
    resources :teams
    resources :jobs
  end
  
  namespace :user do
    root to: "timesheets#index"
    resources :users
    resources :timesheets
    resources :leaves

  end

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :lockable
  paginates_per 10
  
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates :password_confirmation, presence: true, length: {minimum: 8}, :if => :password_required?
  belongs_to :team
  has_many :timesheets
  has_many :leaves
  
  alias_attribute :name, :email

  def full_name
    full_name = "#{first_name} #{last_name}"
    
    full_name.strip.empty? ? "Unknown" : full_name
  end
  
  def details
    team = Team.find_by_id(team_id)
    team_name = team.nil? ? "Unknown" : team.name
    "ID: #{id} - #{full_name} - #{team_name}"
  end
  
  def available_jobs
    self.team.jobs.where.not(state_id: State::TYPES[:completed]).order(:id) if self.team
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController
  before_filter :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end
  
  def create    
    @user = User.create(user_params)

    if @user.save
      flash[:notice] = "New user has been created!"
      UserMailer.welcome_to_strongtie(@user).deliver
      redirect_to admin_users_path
    else
      flash[:error] = "Error when trying to save. Please try again"
      render :new
    end
  end

  def index
    @users = User.all.order(:email).page params[:page]
  end
  
  def update
    sanitize_user_params
    if @user.update_without_password user_params
      flash[:notice] = "User has been updated successfully!"
      redirect_to admin_users_path
    else
      flash[:error] = "Error when trying to update #{@user.email}. Please try again"
      render :edit
    end
  end
  
  def destroy
    if @user != current_user
      @user.destroy
      flash[:notice] = "User has been deleted successfully!"
    else
      flash[:error] = "You can't delete yourself!"
    end
    
    render nothing: true #ajax call will reload index page
  end

  def search
    @users = User.where("email = ? or first_name = ? or last_name = ?", params[:email], params[:first_name], params[:last_name])
    @users = User.all.order(:email) if @users.empty? && search_params_empty?

    @users = @users.page params[:page]
    render :index
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def search_params_empty?
    [:email, :first_name, :last_name].inject(true) {|result, search_param| result && params[search_param].empty? }
  end

  def user_params
    params.require(:user).permit(:email,
                                 :first_name,
                                 :last_name,
                                 :password,
                                 :password_confirmation,
                                 :admin,
                                 :team_id)
  end
  
  def sanitize_user_params
    if user_params[:password].blank?
      user_params.delete :password
      user_params.delete :password_confirmation
    end
  end
end

app/controllers/user/leaves_controller.rb
class User::LeavesController < User::UsersController
  def index
    @leaves = Leave.all.order(leave_date: :desc).page params[:page] 
  end

  def new
    @leave = Leave.new
  end

  def create
    @leave = Leave.create(leave_params)
    @leave.user = @user
    @leave.status = State::LEAVE_TYPE[:new]
    if @leave.save
      flash[:notice] = "New leave has been created successfully!"
      redirect_to user_leaves_path
    else
      flash[:error] = "There is an error when creating new leave. Please try again!"
      render :new
    end
  end

  private

  def leave_params
    params.require(:leave).permit(
      :leave_date,
      :leave_type,
      :duration,
      :reason
    )
  end
end

app/controllers/user/timesheets_controller.rb
class User::TimesheetsController < User::UsersController
  before_filter :set_timesheet, only: [:update, :show, :edit, :destroy]
  def index
    @timesheets = Timesheet.where(user_id: @user.id).order(:working_date => :desc).page params[:page]
  end
  
  def new
    @timesheet = Timesheet.new
  end
  
  def create
    @timesheet = Timesheet.create(timesheet_params)
    @timesheet.user = @user
    if @timesheet.save
      flash[:notice] = "New work log has been created successfully!"
      redirect_to user_timesheets_path
    else
      flash[:error] = "Error when creating work log. Please try again"
      render :new
    end
  end
  
  def update
    respond_to do |format|
      if @timesheet.update timesheet_params
        format.html do
          flash[:notice] = "Work log has been updated successfully!"
          redirect_to user_timesheets_path
        end
        format.json {head :no_content}
      else
        format.html do
          flash[:notice] = "Error when updating work log. Please try again"
          render :edit
        end
        format.json {head 406}
      end
    end
  end
  
  def destroy
    if @timesheet.destroy
      flash[:notice] = "Work log has been deleted successfully!"
    else
      flash[:error] = "Error when deleting work log. Please try again"
    end
    
    render nothing: true
  end
  
  private
  def timesheet_params
    params.require(:timesheet).permit(
      :description,
      :working_date,
      :duration,
      :job_id,
      :work_type
    )
  end
  
  def set_timesheet
    @timesheet = Timesheet.find(params[:id])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_user_layout
  before_filter :set_user
  
  def set_user_layout
    self.class.layout "user/layout"
  end
  
  def update
    if @user.update_without_password user_params
      flash[:notice] = "Your profile has been updated successfully!"
    else
      flash[:error] = "Error when saving your profile. Please try again"
    end

    render :edit
  end
  
  private
  def set_user
    @user = current_user
  end
  
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :picture
    )
  end
end

app/views/admin/users/_confirmation.html.haml
#delete-confirmation.modal.fade{:tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#delete-confirmation.modal-title Delete user
      .modal-body
        Are you sure want to delete?
      .modal-footer
        %button.btn.btn-default#delete-close{"data-dismiss" => "modal", :type => "button"} Cancel
        %button.btn.btn-danger#delete-confirm{":type" => "button"} Delete

:javascript
  $('#delete-confirmation').on('show.bs.modal', function(e) {
    var ajaxDeleteUrl = $(e.relatedTarget).data('href');
    var deleteButton = $(this).find('#delete-confirm').attr('href', $(e.relatedTarget).data('href'));
    deleteButton.click(function() {
      $.ajax({
        data: {"_method": 'delete'},
        type: 'POST',
        url: ajaxDeleteUrl,
        complete: function(data) {
         location.reload(true);
        }
      });
    });
  });
        

app/views/admin/users/_dropdown_team.html.haml
- @all_teams = Team.all
= f.label :team_name, "Belongs to team"
%select.form-control
  %option
  - @all_teams.each do |team|
    %option{:value => "#{team.id}"}
      = team.name

app/views/admin/users/_form.html.haml
= form_for([:admin, @user], html: {class: "form-default"}) do |f|
  = show_error_messages_if_any @user.errors.full_messages
  .form-group
    = f.label :email
    = f.email_field :email, autofocus: true, class: "form-control", disabled: params[:action] == "edit"
  .form-group
    = f.label :first_name
    = f.text_field :first_name, autofocus: true, class: "form-control"
  .form-group
    = f.label :last_name
    = f.text_field :last_name, autofocus: true, class: "form-control"
  .form-group
    = f.label :password
    = f.password_field :password, autocomplete: "off", class: "form-control"
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, autocomplete: "off", class: "form-control"
  .form-group
    = render :partial => "public/common/teams_dropdown", locals: {:f => f, :select_id => @user.team_id}
  .form-group
    = f.check_box :admin, disabled: @user == current_user
    = f.label :admin, "Admin"
  .actions
    %button.btn.btn-primary{:type => "submit"}
      %i.fa.fa-send
        SAVE

app/views/admin/users/edit.html.haml
.container
  .col-sm-6.col-md-offset-3
    %h2 Edit user
    %hr/
    =render partial: "form"

app/views/admin/users/index.html.haml
.container.clearfix
  = show_error_messages_if_any [flash[:error]]
  = show_notice_message_if_any flash[:notice]
  
  #search-form.well
    = form_tag(admin_users_search_path, method: :get) do
      .row
        .form-group.col-md-6
          = text_field_tag :email, params[:email], :placeholder => "Enter email", :type => "email", class: "form-control"
      .row
        .form-group.col-md-6
          = text_field_tag :first_name, params[:first_name], class: "form-control", :placeholder => "First Name", :type => "text"
      .row
        .form-group.col-md-6
          = text_field_tag :last_name, params[:last_name], class: "form-control", :placeholder => "Last Name", :type => "text"
      %button.btn.btn-primary{:type => "submit"}
        %i.fa.fa-search
          Search

  .add-button-link.btn-primary.fa.fa-user-plus
    = link_to "Create new user", new_admin_user_path

  - if @users.any?
    %table.table.table-bordered.table-striped
      - @users.to_a.each do |user|
        = render :partial => "public/common/resource_view", locals: {:resource => user}

    .text-center
      = paginate @users
      
= render :partial => "public/common/confirmation"

app/views/admin/users/new.html.haml
.container
  .col-sm-6.col-md-offset-3
    %h2 Create new user
    %hr/
    =render partial: "form"