config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions' }

  root 'home#index'

  namespace :admin do
    root :to => "users#index"
    get '/users/search' => 'users#search'
    resources :users
    resources :teams
    resources :jobs
  end
  
  namespace :user do
    root to: "timesheets#index"
    resources :users
    resources :timesheets
    resources :leaves

  end

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/views/layouts/_footer.html.haml
%footer
  .container
    %section
      .copyright
        &copy;
        = Date.today.year
        All rights reserved. Authorised by Bang Nguyen
        %br
        %br Phone: +61 422 375 093
        %br Email: thebangnguyen@gmail.com
  = csrf_meta_tag

:javascript
  enableDismiss($(".alert"), $(".closable"));
  $.ajaxSetup({
    headers: {
      'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
    }
  });

app/views/layouts/_head.html.haml
<!DOCTYPE html>
%head
  %meta{:charset => "utf-8"}
  %title
    = "Simpson Strong-Tie® Vietnam"
  = favicon_link_tag "strongtie_logo.jpeg"
  
  = stylesheet_link_tag "application"
  = javascript_include_tag "application"

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#navigator", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a{:href => "http://www.strongtie.com"}
          = image_tag("strongtie_logo.jpeg", :alt => "strongtie-logo")
      #navigator.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "/"} HOME
          - if user_signed_in?
            %li
              =link_to("DASHBOARD", user_root_path)
            - if current_user.admin?
              %li
                =link_to("ADMIN", admin_root_path)
            %li
              = link_to "SIGN OUT", destroy_user_session_path(:authenticity_token => form_authenticity_token()), :method => :delete
          - else
            %li
              %a{:href => new_user_registration_path} SIGN UP
            %li
              %a{:href => new_user_session_path} SIGN IN
          %li
            %a{:href => "http://www.strongtie.com/about/index.html?source=topnav"} ABOUT US

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SSTHrms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
= render :partial => "layouts/head"
%body
  = render :partial => "layouts/header"
  = yield
  = render :partial => "layouts/footer"
  .device-phone.visible-phone
  .device-tablet.visible-tablet
  .device-desktop.visible-desktop